### ISSUE TITLE
UI crash on suspended users

### ISSUE THREAD

**Issue by GiacoR** [clarkwinkelmann/flarum-ext-circle-groups#1]
When there is a suspended user in a discussion, `badges[0].props.style is undefined` in [extension.js, L. 36](https://github.com/clarkwinkelmann/flarum-ext-circle-groups/blob/bfc0dcf96a0d831fffcaa2504855e7ac389323b2/js/forum/dist/extension.js#L36). This crashes the whole UI from that point on.

This might also be a problem in [main.js, L. 23](https://github.com/clarkwinkelmann/flarum-ext-circle-groups/blob/bfc0dcf96a0d831fffcaa2504855e7ac389323b2/js/forum/src/main.js#L23).

To reproduce just suspend a user and look at his discussions, posts or profile.

**Comment by clarkwinkelmann** [comment]
Thanks for the report, didn't know my extension was used at all :yum: 

I made a fix and tagged version 0.1.0-beta.2 You should be able to get it via Composer https://packagist.org/packages/clarkwinkelmann/flarum-ext-circle-groups
